### ISSUE TITLE
Generated files seems to contain incorrect file names/paths

### ISSUE THREAD

**Issue by andrew-buckley** [Azure/autorest.typescript#14]
When generating a client using: `autorest --typescript --output-folder=./ --input-file=./iothub.json  --generate-metadata=true --typescript.azure-arm=
true` I end up having to make several changes before I can successfully run `npm run-script build`.

The first error I get is this:
```
npm run-script build

> @ build F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js

error TS5058: The specified path does not exist: 'tsconfig.node.json'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andbuc\AppData\Roaming\npm-cache\_logs\2017-12-04T18_54_27_484Z-debug.log
```

Looking at the generated output, neither 'tsconfig.node.json' nor 'tsconfig.browser.json' exist. Only 'tsconfig.json' exists. So after making this change to the 'tsc' script in the 'package.json' file I get this:
```
npm run-script build

> @ build F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js

tsconfig.json(19,20): error TS5024: Compiler option 'declaration' requires a value of type boolean.
error TS18003: No inputs were found in config file 'F:/Projects/Ecosystem/azure-rest-api-specs/specification/iothub/resource-manager/Microsoft.Devices/2017-07-01/tsconfig.json'. Specified 'include' paths were '["./lib/**/*.ts","./test/**/*.ts"]' and 'exclude' paths were '["node_modules"]'.
tsconfig.json(19,5): error TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.
tsconfig.json(20,5): error TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andbuc\AppData\Roaming\npm-cache\_logs\2017-12-04T18_54_55_385Z-debug.log
```

In order to fix the above, the following changes were necessary in the 'tsconfig.json' file:

1. Change `"declaration": "true"` to `"declaration": true`
2. Change the `"include"` array to have the correct directory of the generated TS files (it currently points to `"./lib/**/*.ts", "./test/**/*.ts"`.

Next, I get the following:
```
npm run-script build

> @ build F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js

Hash: 9f83505885a3f824ef10
Version: webpack 3.10.0
Time: 32ms

ERROR in Entry module not found: Error: Can't resolve './lib/iotHubClient.ts' in 'F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andbuc\AppData\Roaming\npm-cache\_logs\2017-12-04T18_56_48_028Z-debug.log
```

In order to fix ths above, the following changes were necessary in the 'webpack.config.js' file:

1. Change `entry: './lib/iotHubClient.ts'` to `entry: './output/iotHubClient.ts'`

Next, I get the following:
```
npm run-script build

> @ build F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js

ts-loader: Using typescript@2.6.2 and F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01\tsconfig.json
Hash: 789ccfc2de768b8c2696
Version: webpack 3.10.0
Time: 3554ms
                                     Asset       Size  Chunks                    Chunk Names
                     iotHubClientBundle.js     365 kB       0  [emitted]  [big]  main
                 iotHubClientBundle.js.map     681 kB       0  [emitted]         main
             typings\lib\iotHubClient.d.ts    2.19 kB          [emitted]
             typings\lib\models\index.d.ts    39.3 kB          [emitted]
           typings\lib\models\mappers.d.ts      58 kB          [emitted]
  typings\lib\operations\certificates.d.ts    18.4 kB          [emitted]
         typings\lib\operations\index.d.ts  194 bytes          [emitted]
typings\lib\operations\iotHubResource.d.ts    77.5 kB          [emitted]
    typings\lib\operations\operations.d.ts    4.11 kB          [emitted]
   [0] ./output/models/mappers.ts 60.8 kB {0} [built]
   [3] ./output/iotHubClient.ts 3.68 kB {0} [built]
   [4] ./output/models/index.ts 232 bytes {0} [built]
   [5] ./output/operations/index.ts 538 bytes {0} [built]
   [6] ./output/operations/operations.ts 14.2 kB {0} [built]
   [7] ./output/operations/iotHubResource.ts 223 kB {0} [built]
   [8] ./output/operations/certificates.ts 59.5 kB {0} [built]
    + 2 hidden modules
ERROR: ENOENT: no such file or directory, open 'F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01\bundle.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read_file (F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01\node_modules\uglify-es\bin\uglifyjs:320:19)
    at F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01\node_modules\uglify-es\bin\uglifyjs:167:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01\node_modules\uglify-es\bin\uglifyjs:166:31)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andbuc\AppData\Roaming\npm-cache\_logs\2017-12-04T18_58_48_219Z-debug.log
```

In order to fix ths above, the following changes were necessary in the 'package.json' file:

1. Change `"build": "npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o bundle.min.js bundle.js"` to `"build": "npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o iotHubClientBundle.min.js iotHubClientBundle.js"`

Only then am I able to get `npm run-script build` to complete successfully and produce a bundled typescript sdk for Azure ARM.

**Comment by amarzavery** [comment]
@andrew-buckley - Sorry for this experience. The issues that you mentioned have been fixed long time back. We have a preview version 2.0.67 of `@microsoft.azure/autorest.typescript` that fixes all of the above issues.
This version is in preview and we shall make it the latest version very soon.

Please run the command like this:
D:\sdk\upstream\tmp>autorest --typescript **--output-folder=./lib** --input-file=..\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01\iothub.json --generate-metadata=true --azure-arm **--use=@microsoft.azure/autorest.typescript@2.0.67**

Please note the `--use=` switch, where I explicitly say autorest to use the 2.0.67 version. Also note the `--output-folder=` switch. I explicitly ask autorest to generate the source code in the `./lib` folder, so that it can generate metadata files like `package.json`, `tsconfig.json`, etc. one level above.

I executed npm install after the client was generated and then executed npm run build and everything works like a charm.

```
D:\sdk\upstream\tmp>npm run build

> @ build D:\sdk\upstream\tmp
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o iotHubClientBundle.min.js iotHubClientBundle.js

ts-loader: Using typescript@2.6.2 and D:\sdk\upstream\tmp\tsconfig.json
Hash: e588acbd04a33f147808
Version: webpack 3.10.0
Time: 13959ms
                                     Asset       Size  Chunks                    Chunk Names
                     iotHubClientBundle.js     373 kB       0  [emitted]  [big]  main
                 iotHubClientBundle.js.map     689 kB       0  [emitted]         main
             typings\lib\iotHubClient.d.ts    2.19 kB          [emitted]
             typings\lib\models\index.d.ts    45.7 kB          [emitted]
           typings\lib\models\mappers.d.ts      58 kB          [emitted]
  typings\lib\operations\certificates.d.ts    18.4 kB          [emitted]
         typings\lib\operations\index.d.ts  194 bytes          [emitted]
typings\lib\operations\iotHubResource.d.ts    77.5 kB          [emitted]
    typings\lib\operations\operations.d.ts    4.11 kB          [emitted]
   [0] ./lib/models/mappers.ts 60.8 kB {0} [built]
   [3] ./lib/iotHubClient.ts 3.66 kB {0} [built]
   [4] ./lib/models/index.ts 8.34 kB {0} [built]
   [5] ./lib/operations/index.ts 538 bytes {0} [built]
   [6] ./lib/operations/operations.ts 14.2 kB {0} [built]
   [7] ./lib/operations/iotHubResource.ts 223 kB {0} [built]
   [8] ./lib/operations/certificates.ts 59.5 kB {0} [built]
    + 2 hidden modules

D:\sdk\upstream\tmp>
```

> TIP: To know the latest available package on npm for a given package, please execute

```
npm show  @microsoft.azure/autorest.typescript
```
This will provide you all the available versions.

Let me know if the issue still persists.

**Comment by amarzavery** [comment]
UPDATE: We made 2.0.67 as the latest version for the typescript generator.
So please execute `autorest -reset`, this should reset the cache at `C:\Users\(Username)\.autorest`.

Then execute the command to generate the TS client. No need to specify the `--use=` switch. autorest should install the latest version of the typescript generator and use that to generate the client.

Let me know if you see further issues.

**Comment by amarzavery** [comment]
In the new version we have also added support for enum. This should improve developer experience.

**Comment by andrew-buckley** [comment]
Awesome, I'll try this out.

**Comment by andrew-buckley** [comment]
Hey @amarzavery, we're still having a few issues after following the above steps. 

```
autorest --reset
AutoRest code generation utility [version: 2.0.4215]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
No configuration found at 'file:///C:/Users/andbuc/.autorest/'.
```

```
$ autorest --typescript --output-folder=/f/Projects/Ecosystem/azure-rest-api-specs/specification/iothub/resource-manage
r/Microsoft.Devices/2017-07-01/output --input-file=iothub.json  --generate-metadata=true --typescript.azure-arm=true
AutoRest code generation utility [version: 2.0.4215]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
No configuration found at 'file:///F:/Projects/Ecosystem/azure-rest-api-specs/specification/iothub/resource-manager/Microsoft.Devices/2017-07-01/'.
   Installing AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23)
```

```
$ npm run-script build

> @ build F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o iotHubClientBundle.min.js iotHubClientBundle.js

error TS18003: No inputs were found in config file 'F:/Projects/Ecosystem/azure-rest-api-specs/specification/iothub/resource-manager/Microsoft.Devices/2017-07-01/tsconfig.json'. Specified 'include' paths were '["./lib/**/*.ts","./test/**/*.ts"]' and 'exclude' paths were '["node_modules"]'.
Hash: 9f83505885a3f824ef10
Version: webpack 3.10.0
Time: 53ms

ERROR in Entry module not found: Error: Can't resolve './lib/iotHubClient.ts' in 'F:\Projects\Ecosystem\azure-rest-api-specs\specification\iothub\resource-manager\Microsoft.Devices\2017-07-01'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o iotHubClientBundle.min.js iotHubClientBundle.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andbuc\AppData\Roaming\npm-cache\_logs\2017-12-14T00_11_55_843Z-debug.log
```

**Comment by RikkiGibson** [comment]
Please reopen if this is still a problem.
